# This YAML file defines the relationship and deployment ordering of your environments.

# The name of the pipeline
name: pipeline-kochi-parinay1987-copilot-kochi-aws-UG

# The version of the schema used in this template
version: 1

# This section defines the source artifacts.
source:
  # The name of the provider that is used to store the source artifacts.
  provider: GitHub
  # Additional properties that further specifies the exact location
  # the artifacts should be sourced from. For example, the GitHub provider
  # has the following properties: repository, branch.
  properties:
    access_token_secret: github-token-kochi-copilot-kochi-aws-UG
    branch: master
    repository: https://github.com/parinay1987/copilot-kochi-aws-UG

# The deployment section defines the order the pipeline will deploy
# to your environments.
stages:
    - # The name of the environment to deploy to.
      name: test
      # Optional: use test commands to validate this stage of your build.
      # test_commands: [echo 'running tests', make test]

